Add arabic translation
ct-js/ct-js-site pull request #43
Opened 2023-12-24 12:03 UTC by wesamdev

we change font to cairo
and i 45% translated

2023-12-25 09:43 UTC, CosmoMyzrailGorynych requested changes

2023-12-25 09:43 UTC, CosmoMyzrailGorynych commented on src/styles/index.styl
> +fonts = font = 'Cairo', sans-serif, serif
Change it to `'Open Sans', 'Cairo', sans-serif, serif` if you need this font for Arabic. Breaking the visual style of all the other languages to support your own is bullshit.

2023-12-25 09:43 UTC, CosmoMyzrailGorynych commented on src/styles/index.styl
> +
This is a wrong place for a font. Add it as a `<link>` tag here: https://github.com/ct-js/ct-js-site/blob/master/src/_includes/head.pug#L20

2023-12-26 17:31 UTC, wesamdev commented on src/styles/index.styl
> +fonts = font = 'Cairo', sans-serif, serif
ok

2023-12-26 18:10 UTC, wesamdev commented
> we change font to cairo and i 45% translated

Font change for arabic
about 55% translated

2023-12-26 18:41 UTC, wesamdev commented
about 65% translated

2024-01-17 21:33 UTC, aymennasri requested changes
Fixed some wrong translations and translated some other lines, will hopefully continue the rest this night or tomorrow.

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        appImageInstructions: 'Run chmod +x for this file (mark as an executable) and run the file. Can be used for updates, too!',
```suggestion
        appImageInstructions: ' شغل chmod +x (لتشغيله). يمكن استعمال الملف للتحديث ايضا',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        shInstructions: 'Unzip, run chmod +x for this file (mark as an executable) and run the file. Can be used for updates, too!',
```suggestion
        shInstructions: 'استخرج و شغل chmod +x (لتشغيله). يمكن استعمال الملف للتحديث ايضا',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        macInstructions: 'غير مجرب استخدمة على مسؤوليتك!',
```suggestion
        macInstructions: 'غير مجرب لكنه يشتغل, استخدمه على مسؤوليتك!',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        macDamagedWarning: 'MacOS on ARM processors may tell that ct.js file is broken, when it\'s not.',
```suggestion
        macDamagedWarning: 'ماك اوس لARM قد يخبرك ان ct.js ملف لا يعمل برغم ان ذلك الخطأ',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        macDamagedLink: 'شوف هذه الصفحة للحل.',
```suggestion
        macDamagedLink: 'افتح الصفحة لمعرفة كيفية حل الخطأ',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        getFromItch: 'Get ct.js on itch.io',
```suggestion
        getFromItch: 'احصل على ct.js على itch.io',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
Github apparently doesn't support Arabic formatting where it should be written from right to left in a way that messes up the formatting when combined with latin languages but this should convey the meaning nevertheless.

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/footer.js
> +        forkUs: 'Fork us on GitHub!',
```suggestion
        forkUs: 'فورك المشروع على GitHub',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/footer.js
> +        joinTelegram: 'Follow the news in ComigoGames\' Telegram channel!',
```suggestion
        joinTelegram: 'تابع الأخبار على قناة التيليغرام ComigoGames ',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/footer.js
> +        vkontakte: 'Follow news in Vkontakte'
```suggestion
        vkontakte: 'تابع الأخبار على Vkontakte'
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/joinGamedev.js
> +        joinGamedev: 'انضم الي العالم  تطوير الألعاب',
```suggestion
        joinGamedev: 'انضم الى عالم  تطوير الألعاب',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/joinGamedev.js
> +        gamedevIsFree: 'انه مجانا!',
```suggestion
        gamedevIsFree: 'انه مجاني!',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/madeWithCtjs.js
> +        pageDescription: 'العاب صنعت ب ct.js, محرك العاب مجاني 2دي معتمد على تكنولوجيا الويب.',
```suggestion
        pageDescription: 'العاب صنعت ب ct.jsمحرك العاب 2دي مجاني معتمد على تكنولوجيا الويب.',
```

2024-01-17 21:33 UTC, aymennasri commented on src/_data/i18n/shareBlock.js
> +        helpCtGrow: 'ساعد ct.js نمو!',
```suggestion
        helpCtGrow: 'ساعد ct.js على النمو!',
```

2024-01-17 23:08 UTC, aymennasri requested changes

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            latest: 'Latest in the Devlog',
```suggestion
            latest: 'مستجدات البرمجة',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            or: 'او',
```suggestion
            or: 'أو',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            joinServer: 'Join their Discord server',
```suggestion
            joinServer: 'Discord انضم لسيرفير',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        allFeatures: 'All the features',
```suggestion
        allFeatures: 'كل الخاصيات',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            customJS: 'امكانية تخصيص JS',
```suggestion
            customJS: 'JavaScript امكانية تخصيص',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            fx: 'نظام تاثيرات و اضواء',
```suggestion
            fx: 'نظام تأثيرات و أضواء',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        everythingYouNeedHeader: 'ct.js لدية كل شي لبناء لعبة',
```suggestion
        everythingYouNeedHeader: 'لديه كل شيئ لبناء لعبة ct.js',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            docs: 'Notes & docs in a side panel, on every screen',
```suggestion
            docs: 'ملاحظات وثائق في نافذة جانبية في كل شاشة',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            collisionHandling: 'Arcade collisions and 2D physics libraries',
```suggestion
            collisionHandling: 'تصادمات اركايد و مكتبات فيزياء ثنائية الابعاد',
```

2024-01-17 23:08 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        madeWithCtjs: 'صنع ب ct.js',
```suggestion
        madeWithCtjs: 'ct.js صنع ب',
```

2024-01-17 23:34 UTC, aymennasri requested changes

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        logoAlt: 'A ct.js logo. Ct.js is a free alternative to Game Maker, Construct and others',
```suggestion
        logoAlt: 'Game Maker, Construct,... هو بديل ل ct.js ,ct.js لوجو',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        yourNewEditor: 'محرك العابك الجديد',
```suggestion
        yourNewEditor: 'محرك ألعابك الجديد',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        lovedBy: ' انه مجاني محبوب من قبل المتبدئين و الطلاب و المبرمجين المستقلين.',
```suggestion
        lovedBy: 'انه مجاني محبوب من قبل المبتدئين و الطلاب و المبرمجين المستقلين',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        punchline: 'ct.js makes learning programming fun and game development easy by its visual tools, good docs and flexible, modular library.',
```suggestion
        punchline: 'يجعل تعلم البرمجة ممتعا و  تطوير الألعاب سهلا بأدواته المرئية، وثائقه الجيدة و مكتبة الوحدات. ct.js',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        download: 'تنزيل',
```suggestion
        download: 'تحميل',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        beginnerFriendlyParagraph: 'يمكنك تحرير الاكواد بشكل مبسط ومناسب للمتبدئين.',
```suggestion
        beginnerFriendlyParagraph: 'يمكنك تحرير الاكواد بشكل مبسط ومناسب للمبتدئين',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/header.js
> +        download: 'تنزيل',
```suggestion
        download: 'تحميل',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/header.js
> +        language: 'عربي'
```suggestion
        language: 'عربية'
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        pageTitle: 'Ct.js — محرك العاب مجاني',
```suggestion
        pageTitle: 'محرك ألعاب مجاني — Ct.js',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        pageDescription: 'محرك العاب مجاني 2دي معتمد على تكنولوجيا الويب.',
```suggestion
        pageDescription: 'محرك ألعاب مجاني ثنائي الأبعاد معتمد على تكنولوجيا الويب',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        yourNewEditor: 'محرك العابك الجديد',
```suggestion
        yourNewEditor: 'محرك ألعابك الجديد',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        logoAlt: 'A ct.js logo. Ct.js is a free alternative to Game Maker, Construct and others',
```suggestion
        logoAlt: 'و غيرهم Construct و Gamer Maker هو بديل مجاني ل Ct.js ,ct.js لوجو',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        lovedBy: ' انه مجاني محبوب من قبل المتبدئين و الطلاب و المبرمجين المستقلين.',
```suggestion
        lovedBy: 'انه مجاني محبوب من قبل المبتدئين و الطلاب و المبرمجين المستقلين',
```

2024-01-17 23:34 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        download: 'تنزيل',
```suggestion
        download: 'تحميل',
```

2024-01-17 23:37 UTC, aymennasri commented
Update : Not used to the mobile app for GitHub and somehow requested changes separately twice or thrice, it should be complete and I'll translate the rest of the lines when you approve my changes.
You could also contact me to further assist with the display of the language.

2024-01-18 10:59 UTC, aymennasri approved these changes

2024-01-18 19:20 UTC, wesamdev reviewed
Thanks

2024-01-18 19:20 UTC, wesamdev commented on src/_data/i18n/downloadPage.js
Great

2024-01-18 19:56 UTC, aymennasri commented on src/_data/i18n/downloadPage.js
> +        linuxInstructions: './ctjs' كمفعل وشغل \'ctjs\' استخرج و ضع'
There's an error here with the anti slash before the single quote, you should try and fix it because the arabic text in the middle is outisde the quotes.

2024-01-19 14:14 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        gamesOfAnyGenreSub: 'Shooters, arcades, adventures, survivals, puzzles, visual novels — you name it!',
```suggestion
        gamesOfAnyGenreSub: 'ألعاب الأسلحة، الأركايد، المغامرات، سرفايفل، الألغاز، الروايات المرئية - أيا كان ما تريد',
```

2024-01-19 14:26 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        welcomeToTheVOIDParagraph: 'A story about rebooting the universe. Swim through the endless dark cosmos, engage in space combat, land on planets for expedition missions and explore the lost te
```suggestion
        welcomeToTheVOIDParagraph: 'قصة حول إعادة إحياء للكون، عم في الظلمات الكونية اللامتناهية، شارك في معارك الفضاء و اذهب للكواكب في حملة مهام و اكتشف التكنولوجيات الضائعة',
```

2024-01-19 14:31 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        illFatedParagraph: 'A vampire-survivor-esque shooter where your character only grows weaker through time. Fend off endless monsters and see how many curses you can get before you succumb to t
```suggestion
        illFatedParagraph: 'لعبة رمي للأسلحة و نجاة مصاص دماء أين تضعف شخصيتك بالوقت، صد الوحوش اللامتناهية و اجمع اللعنات حتى تخضع للأعداء',
```

2024-01-19 14:36 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        vacationOfFusionParagraph: 'A light-hearted island-building game where you mix elements to create new tiles. Features creative mode, cartoony graphics, and a selfie mode!',
```suggestion
        vacationOfFusionParagraph: 'لعبة ممتعة لبناء الجزر أين تخلط عناصر لتكوين بلاط جديد، تتضمن وضعا ابداعيا، رسوما كرتونية و وضع سيلفي',
```

2024-01-19 14:37 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            codeEditor: 'محرر اكواد',
```suggestion
            codeEditor: 'محرر أكواد',
```

2024-01-19 14:37 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            collisionHandling: 'تصادمات اركايد و مكتبات فيزياء ثنائية الابعاد',
```suggestion
            collisionHandling: 'تصادمات أركايد و مكتبات فيزياء ثنائية الابعاد',
```

2024-01-19 14:38 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            animations: 'انميشن',
```suggestion
            animations: 'أنميشن',
```

2024-01-19 14:38 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            docs: 'ملاحظات وثائق في نافذة جانبية في كل شاشة',
```suggestion
            docs: 'ملاحظات و وثائق في نافذة جانبية في كل شاشة',
```

2024-01-19 14:38 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        partners: 'شريكنا',
```suggestion
        partners: 'شركاؤنا',
```

2024-01-19 14:39 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            description: 'Mini Jam is an open recurring game jam that is held every two weeks on itch.io.',
```suggestion
            description: 'itch.io لعبة مفتوحة كل أسبوعين على Mini Jam',
```

2024-01-19 14:40 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +            readMore: 'اقرا المزيد…',
```suggestion
            readMore: '...اقرا المزيد',
```

2024-01-19 14:40 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        supportOnPatreon: 'ادعم المشروع عن طريق Patreon',
```suggestion
        supportOnPatreon: 'Patreon ادعم المشروع على',
```

2024-01-19 14:41 UTC, aymennasri commented on src/_data/i18n/whatsnext.js
> +        completeTutorials: 'دروس كاملة لتعلم كيفية العمل. توضح دروسنا التعليمية كيفية إنشاء ألعاب كاملة ، وشرح ما يتم فعله ولماذا بالتفصيل.',
```suggestion
        completeTutorials: 'دروس كاملة لتعلم كيفية العمل. توضح دروسنا التعليمية كيفية إنشاء ألعاب كاملة ، وشرح ما يتم فعله ولماذا بالتفصيل',
```

2024-01-19 14:46 UTC, aymennasri approved these changes
Should be good to go, you only have to figure out the font now.

2024-01-23 04:58 UTC, CosmoMyzrailGorynych commented
These are still untranslated:

Keys found here: https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L23-L29

![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/62b85b5b-d7f5-4e3c-a4f5-dbf952d5b399)

One key from here: https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L50

![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/5b91ce7d-13da-4036-aa37-c1e5d5e64e98)

A key from here: https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L16

![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/e36964ff-bcb9-4983-a9a1-3c2d14503c86)

@wesamdev @aymennasri

2024-01-23 05:36 UTC, CosmoMyzrailGorynych commented
Also note that `ct.js` is **always** in lowercase, unless it is in the beginning of a sentence.

2024-01-23 05:37 UTC, CosmoMyzrailGorynych commented
Trying to add RTL support to the site rn @_@

2024-01-23 08:17 UTC, CosmoMyzrailGorynych commented
@wesamdev @aymennasri I pushed some RTL improvements to this PR. Let me know if something needs to be tweaked, I never worked with RTL layouts.

2024-01-23 09:41 UTC, aymennasri commented
> These are still untranslated:
> 
> Keys found here: https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L23-L29
> 
> ![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/62b85b5b-d7f5-4e3c-a4f5-dbf952d5b399)
> 
> One key from here: https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L50
> 
> ![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/5b91ce7d-13da-4036-aa37-c1e5d5e64e98)
> 
> A key from here: https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L16
> 
> ![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/e36964ff-bcb9-4983-a9a1-3c2d14503c86)
> 
> @wesamdev @aymennasri 

I did translate them, you just have to approve the last changes i requested.

2024-01-23 11:36 UTC, wesamdev commented
> [L29](https://github.com/ct-js/ct-js-site/blob/master/src/_data/i18n/homepage.js#L23-L29)
> 
> ![изображение](https://private-user-images.githubusercontent.com/3174357/298809259-62b85b5b-d7f5-4e3c-a4f5-dbf952d5b399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDkzNzUsIm5iZiI6MTcwNjAwOTA3NSwicGF0aCI6Ii8zMTc0MzU3LzI5ODgwOTI1OS02MmI4NWI1Yi1kN2Y1LTRlM2MtYTRmNS1kYmY5NTJkNWIzOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTEyNDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM1ZDVjZDBhMzAwNDk3YWU0NDg4NTRkYzZiMTZjMzFkYjIzMDdlMDcxMWMxZTJlZTBmMGQyZmE3NTAxMmEzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jVhGbgwlqBgbpgBT8micBfMHeA0d8AGoU-Y7kYLP3Qg)

Ok

2024-01-23 21:10 UTC, aymennasri approved these changes
Should be done, please commit all changes next time.

2024-01-23 21:10 UTC, aymennasri commented on src/_data/i18n/madeWithCtjs.js
> +        pageDescription: 'العاب صنعت ب ct.js, محرك العاب مجاني 2دي معتمد على تكنولوجيا الويب.',
```suggestion
        pageDescription: 'محرك ألعاب ثنائي الأبعاد معتمد على تكنولوجيا الويب ،ct.js ألعاب صنعت ب',
```

2024-01-23 21:10 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        punchline: 'يجعل تعلم البرمجة ممتعا و  تطوير الألعاب سهلا بأدواته المرئية، وثائقه الجيدة و مكتبة الوحدات. ct.js',
```suggestion
        punchline: 'يجعل تعلم البرمجة ممتعا و تطوير الألعاب سهلا بأدواته المرئية، وثائقه الجيدة و مكتبة الوحدات ct.js',
```

2024-01-23 21:10 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        smoothWorkflowHeader: 'بيئة عمل سلسه',
```suggestion
        smoothWorkflowHeader: 'بيئة عمل سلسة',
```

2024-01-23 21:10 UTC, aymennasri commented on src/_data/i18n/homepage.js
> +        vacationOfFusionParagraph: 'A light-hearted island-building game where you mix elements to create new tiles. Features creative mode, cartoony graphics, and a selfie mode!',
```suggestion
        vacationOfFusionParagraph: 'لعبة بناء جزيرة ممتعة أين تمزج العناصر لتكوين بلاط جديد، فيها وضع ابداعي، رسوم متحركة و وضع سيلفي',
```

2024-01-23 21:10 UTC, aymennasri commented on src/_data/i18n/footer.js
> +        appLicense: 'MIT مرخص تحت رخصة  ct.js تطبيق',
```suggestion
        appLicense: 'MIT مرخص تحت رخصة ct.js تطبيق',
```

2024-01-24 08:52 UTC, CosmoMyzrailGorynych commented
These lost at least half of their meaning. Nothing about desktop builds, languages used, docs, etc.

![изображение](https://github.com/ct-js/ct-js-site/assets/3174357/5ef1aa51-932f-4f2d-aa3b-ea6367701953)

2024-01-24 09:12 UTC, CosmoMyzrailGorynych requested changes
The cards under the first cut (see in my latest screenshot) lost ~70% of their meaning.

2024-01-25 16:10 UTC, aymennasri commented
@CosmoMyzrailGorynych I'm only translating what's left in English in each "ar" section so yeah, and there's always a problem where some of my requested changes aren't approved causing me to start over with already translated texts; I'm waiting for all the changes to get committed then I'll be reviewing each section to hopefully complete this.

2024-01-26 09:49 UTC, CosmoMyzrailGorynych commented
@aymennasri I see three change requests on this page rn, should they all be merged?

2024-01-27 12:02 UTC, aymennasri commented
@CosmoMyzrailGorynych Of course.

2024-01-28 18:19 UTC, wesamdev commented
> The cards under the first cut (see in my latest screenshot) lost ~70% of their meaning.
Bro lang is the diffrent

2024-02-09 00:48 UTC, CosmoMyzrailGorynych commented
I'm merging it as is because I'm lost in this PR, and I don't want this PR to hang unmerged indefinitely. Please send improvements to this site locale in separate PRs.

2024-02-09 00:49 UTC, merged

2024-02-11 10:09 UTC, wesamdev commented
Ok